version: "2"
linters:
  enable:
    - gocritic
    - gosec
  settings:
    gosec:
      excludes:
        - G602
    gocritic:
      disabled-checks:
        - commentedOutCode
        - paramTypeCombine
        - ifElseChain
        - unnamedResult
      enabled-tags:
        - performance
        - diagnostic
        - opinionated
      settings:
        rangeExprCopy:
          sizeThreshold: 24
        rangeValCopy:
          sizeThreshold: 24
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
