// Generated by ego.
// DO NOT EDIT

//line nav.ego:1

package webui

import "fmt"
import "html"
import "io"
import "context"

import (
	"net/http"
	"strings"

	"github.com/contribsys/faktory/client"
)

func ego_nav(w io.Writer, req *http.Request) {

//line nav.ego:13
	_, _ = io.WriteString(w, "\n<div class=\"navbar navbar-default navbar-fixed-top\">\n  <div class=\"container-fluid\">\n    <div class=\"navbar-header\" data-navbar=\"static\">\n      <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar-menu\">\n        <span class=\"icon-bar\"></span>\n        <span class=\"icon-bar\"></span>\n        <span class=\"icon-bar\"></span>\n      </button>\n      <div class=\"navbar-toggle collapsed navbar-livereload\">\n      </div>\n      <a class=\"navbar-brand\" href=\"")
//line nav.ego:23
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(root(req))))
//line nav.ego:23
	_, _ = io.WriteString(w, "/\">\n        <span class=\"status\">\n          ")
//line nav.ego:25
	x := currentStatus(req)
//line nav.ego:26
	_, _ = io.WriteString(w, "\n          <i class=\"status-sprite status-")
//line nav.ego:26
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(x)))
//line nav.ego:26
	_, _ = io.WriteString(w, "\" style=\"background-image: url(")
//line nav.ego:26
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(root(req))))
//line nav.ego:26
	_, _ = io.WriteString(w, "/static/img/status.png);\"></i>\n        </span>\n        ")
//line nav.ego:28
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(client.Name)))
//line nav.ego:29
	_, _ = io.WriteString(w, "\n      </a>\n    </div>\n\n    <div class=\"collapse navbar-collapse\" id=\"navbar-menu\">\n      <ul class=\"nav navbar-nav\" data-navbar=\"static\">\n        ")
//line nav.ego:34
	for _, tab := range DefaultTabs {
		if tab.Path == "/" {
//line nav.ego:36
			_, _ = io.WriteString(w, "\n            <li class=\"")
//line nav.ego:36
			if req.RequestURI == "/" {
//line nav.ego:36
				_, _ = io.WriteString(w, "active")
//line nav.ego:36
			}
//line nav.ego:36
			_, _ = io.WriteString(w, "\">\n          ")
//line nav.ego:37
		} else {
//line nav.ego:38
			_, _ = io.WriteString(w, "\n            <li class=\"")
//line nav.ego:38
			if strings.HasPrefix(req.RequestURI, tab.Path) {
//line nav.ego:38
				_, _ = io.WriteString(w, "active")
//line nav.ego:38
			}
//line nav.ego:38
			_, _ = io.WriteString(w, "\">\n          ")
//line nav.ego:39
		}
//line nav.ego:40
		_, _ = io.WriteString(w, "\n            <a href=\"")
//line nav.ego:40
		_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(relative(req, tab.Path))))
//line nav.ego:40
		_, _ = io.WriteString(w, "\">")
//line nav.ego:40
		_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(t(req, tab.Name))))
//line nav.ego:40
		_, _ = io.WriteString(w, "</a>\n          </li>\n        ")
//line nav.ego:42
	}
//line nav.ego:43
	_, _ = io.WriteString(w, "\n      </ul>\n      <ul class=\"nav navbar-nav navbar-right navbar-livereload\" data-navbar=\"static\">\n        <li>\n        </li>\n      </ul>\n    </div>\n    <span class=\"status-text\">\n      <i class=\"status-icon status-")
//line nav.ego:50
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(x)))
//line nav.ego:50
	_, _ = io.WriteString(w, "\"></i>\n      ")
//line nav.ego:51
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(t(req, x))))
//line nav.ego:52
	_, _ = io.WriteString(w, "\n    </span>\n  </div>\n</div>\n")
//line nav.ego:55
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
