// Generated by ego.
// DO NOT EDIT

//line nav.ego:1

package webui

import "fmt"
import "html"
import "io"
import "context"

import (
	"net/http"
	"strings"
)

func ego_nav(w io.Writer, req *http.Request) {

//line nav.ego:11
	_, _ = io.WriteString(w, "\n<div class=\"fixed-top bg-light navbar-default\">\n  <div class=\"container-fluid\">\n    <div class=\"navbar navbar-light navbar-fixed-top navbar-expand-md py-0\">\n      <a class=\"navbar-brand flex-grow-1\" href=\"")
//line nav.ego:14
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(root(req))))
//line nav.ego:14
	_, _ = io.WriteString(w, "/\">\n        <span class=\"status\">\n          ")
//line nav.ego:16
	x := currentStatus(req)
//line nav.ego:17
	_, _ = io.WriteString(w, "\n          <i class=\"status-sprite status-")
//line nav.ego:17
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(x)))
//line nav.ego:17
	_, _ = io.WriteString(w, "\" style=\"background-image: url(")
//line nav.ego:17
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(root(req))))
//line nav.ego:17
	_, _ = io.WriteString(w, "/static/img/status.png);\"></i>\n        </span>\n        ")
//line nav.ego:19
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(productTitle(req))))
//line nav.ego:20
	_, _ = io.WriteString(w, "\n      </a>\n\n      <span class=\"status-text\">\n        <i class=\"status-icon status-")
//line nav.ego:23
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(x)))
//line nav.ego:23
	_, _ = io.WriteString(w, "\"></i>\n        ")
//line nav.ego:24
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(t(req, x))))
//line nav.ego:25
	_, _ = io.WriteString(w, "\n      </span>\n\n      <button class=\"navbar-toggler ms-3\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbar-menu\" aria-controls=\"navbar-menu\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n        <span class=\"navbar-toggler-icon\"></span>\n      </button>\n\n      <div class=\"collapse navbar-collapse justify-content-center\" id=\"navbar-menu\">\n        <ul class=\"navbar-nav\" data-navbar=\"static\">\n          ")
//line nav.ego:33
	for _, tab := range DefaultTabs {
		if tab.Path == "/" {
//line nav.ego:35
			_, _ = io.WriteString(w, "\n              <li class=\"nav-item")
//line nav.ego:35
			if req.RequestURI == "/" {
//line nav.ego:35
				_, _ = io.WriteString(w, " active")
//line nav.ego:35
			}
//line nav.ego:35
			_, _ = io.WriteString(w, "\">\n            ")
//line nav.ego:36
		} else {
//line nav.ego:37
			_, _ = io.WriteString(w, "\n              <li class=\"nav-item")
//line nav.ego:37
			if strings.HasPrefix(req.RequestURI, tab.Path) {
//line nav.ego:37
				_, _ = io.WriteString(w, " active")
//line nav.ego:37
			}
//line nav.ego:37
			_, _ = io.WriteString(w, "\">\n            ")
//line nav.ego:38
		}
//line nav.ego:39
		_, _ = io.WriteString(w, "\n              <a class=\"nav-link p-3\" href=\"")
//line nav.ego:39
		_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(relative(req, tab.Path))))
//line nav.ego:39
		_, _ = io.WriteString(w, "\">")
//line nav.ego:39
		_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(t(req, tab.Name))))
//line nav.ego:39
		_, _ = io.WriteString(w, "</a>\n            </li>\n          ")
//line nav.ego:41
	}
//line nav.ego:42
	_, _ = io.WriteString(w, "\n        </ul>\n      </div>\n    </div>\n  </div>\n</div>\n")
//line nav.ego:47
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
