// Generated by ego.
// DO NOT EDIT

//line paging.ego:1

package webui

import "fmt"
import "html"
import "io"
import "context"

import (
	"math"
	"net/http"
)

func ego_paging(w io.Writer, req *http.Request, url string, total_size, count, current_page uint64) {

//line paging.ego:11
	_, _ = io.WriteString(w, "\n\n")
//line paging.ego:12
	if total_size > count {
//line paging.ego:13
		_, _ = io.WriteString(w, "\n  <ul class=\"pagination\">\n    <li class=\"page-item")
//line paging.ego:14
		if current_page == 1 {
//line paging.ego:14
			_, _ = io.WriteString(w, " disabled")
//line paging.ego:14
		}
//line paging.ego:14
		_, _ = io.WriteString(w, "\">\n      <a class=\"page-link\" href=\"")
//line paging.ego:15
		_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(relative(req, url))))
//line paging.ego:15
		_, _ = io.WriteString(w, "?page=1\">&laquo;</a>\n    </li>\n    ")
//line paging.ego:17
		if current_page > 1 {
//line paging.ego:18
			_, _ = io.WriteString(w, "\n      <li class=\"page-item\">\n        <a class=\"page-link\" href=\"")
//line paging.ego:19
			_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(relative(req, url))))
//line paging.ego:19
			_, _ = io.WriteString(w, "?")
//line paging.ego:19
			_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(pageparam(req, current_page-1))))
//line paging.ego:19
			_, _ = io.WriteString(w, "\">")
//line paging.ego:19
			_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(current_page-1)))
//line paging.ego:19
			_, _ = io.WriteString(w, "</a>\n      </li>\n    ")
//line paging.ego:21
		}
//line paging.ego:22
		_, _ = io.WriteString(w, "\n    <li class=\"page-item disabled\">\n      <a class=\"page-link\" href=\"")
//line paging.ego:23
		_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(relative(req, url))))
//line paging.ego:23
		_, _ = io.WriteString(w, "?")
//line paging.ego:23
		_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(pageparam(req, current_page))))
//line paging.ego:23
		_, _ = io.WriteString(w, "\">")
//line paging.ego:23
		_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(current_page)))
//line paging.ego:23
		_, _ = io.WriteString(w, "</a>\n    </li>\n    ")
//line paging.ego:25
		if total_size > current_page*count {
//line paging.ego:26
			_, _ = io.WriteString(w, "\n      <li class=\"page-item\">\n        <a class=\"page-link\" href=\"")
//line paging.ego:27
			_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(relative(req, url))))
//line paging.ego:27
			_, _ = io.WriteString(w, "?")
//line paging.ego:27
			_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(pageparam(req, current_page+1))))
//line paging.ego:27
			_, _ = io.WriteString(w, "\">")
//line paging.ego:27
			_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(current_page+1)))
//line paging.ego:27
			_, _ = io.WriteString(w, "</a>\n      </li>\n    ")
//line paging.ego:29
		}
//line paging.ego:30
		_, _ = io.WriteString(w, "\n    <li class=\"page-item")
//line paging.ego:30
		if total_size <= current_page*count {
//line paging.ego:30
			_, _ = io.WriteString(w, " disabled")
//line paging.ego:30
		}
//line paging.ego:30
		_, _ = io.WriteString(w, "\">\n      <a class=\"page-link\" href=\"")
//line paging.ego:31
		_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(relative(req, url))))
//line paging.ego:31
		_, _ = io.WriteString(w, "?")
//line paging.ego:31
		_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(pageparam(req, uint64(math.Ceil(float64(total_size)/float64(count)))))))
//line paging.ego:31
		_, _ = io.WriteString(w, "\">&raquo;</a>\n    </li>\n  </ul>\n")
//line paging.ego:34
	}
//line paging.ego:35
	_, _ = io.WriteString(w, "\n")
//line paging.ego:35
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
