// Generated by ego.
// DO NOT EDIT

//line scheduled_job.ego:1

package webui

import "fmt"
import "html"
import "io"
import "context"

import (
	"net/http"

	"github.com/contribsys/faktory/client"
)

func ego_scheduled_job(w io.Writer, req *http.Request, key string, job *client.Job) {
	ego_layout(w, req, func() {
//line scheduled_job.ego:12
		_, _ = io.WriteString(w, "\n\n")
//line scheduled_job.ego:13
		ego_job_info(w, req, job)
//line scheduled_job.ego:14
		_, _ = io.WriteString(w, "\n\n<form class=\"form-horizontal\" action=\"")
//line scheduled_job.ego:15
		_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(root(req))))
//line scheduled_job.ego:15
		_, _ = io.WriteString(w, "/scheduled/")
//line scheduled_job.ego:15
		_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(key)))
//line scheduled_job.ego:15
		_, _ = io.WriteString(w, "\" method=\"post\">\n  ")
//line scheduled_job.ego:16
		_, _ = fmt.Fprint(w, csrfTag(req))
//line scheduled_job.ego:17
		_, _ = io.WriteString(w, "\n  <div>\n    <a class=\"btn btn-default\" href=\"")
//line scheduled_job.ego:18
		_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(root(req))))
//line scheduled_job.ego:18
		_, _ = io.WriteString(w, "/scheduled\">")
//line scheduled_job.ego:18
		_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(t(req, "GoBack"))))
//line scheduled_job.ego:18
		_, _ = io.WriteString(w, "</a>\n    <button class=\"btn btn-primary\" type=\"submit\" name=\"action\" value=\"add_to_queue\">")
//line scheduled_job.ego:19
		_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(t(req, "AddToQueue"))))
//line scheduled_job.ego:19
		_, _ = io.WriteString(w, "</button>\n    <button class=\"btn btn-danger\" type=\"submit\" name=\"action\" value=\"delete\">")
//line scheduled_job.ego:20
		_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(t(req, "Delete"))))
//line scheduled_job.ego:20
		_, _ = io.WriteString(w, "</button>\n  </div>\n</form>\n\n")
//line scheduled_job.ego:24
	})
//line scheduled_job.ego:25
	_, _ = io.WriteString(w, "\n")
//line scheduled_job.ego:25
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
