// Generated by ego.
// DO NOT EDIT

//line summary.ego:1

package webui

import "fmt"
import "html"
import "io"
import "context"

import "net/http"

func ego_summary(w io.Writer, req *http.Request) {
	c := req.Context()
	store := ctx(req).Store()

//line summary.ego:10
	_, _ = io.WriteString(w, "\n<ul class=\"list-unstyled summary row justify-content-around\">\n  <li class=\"processed col-12 col-md-auto\">\n    <span class=\"count\">")
//line summary.ego:12
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(uintWithDelimiter(store.TotalProcessed(c)))))
//line summary.ego:12
	_, _ = io.WriteString(w, "</span>\n    <span class=\"desc\">")
//line summary.ego:13
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(t(req, "Processed"))))
//line summary.ego:13
	_, _ = io.WriteString(w, "</span>\n  </li>\n  <li class=\"failed col-12 col-md-auto\">\n    <span class=\"count\">")
//line summary.ego:16
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(uintWithDelimiter(store.TotalFailures(c)))))
//line summary.ego:16
	_, _ = io.WriteString(w, "</span>\n    <span class=\"desc\">")
//line summary.ego:17
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(t(req, "Failed"))))
//line summary.ego:17
	_, _ = io.WriteString(w, "</span>\n  </li>\n  <li class=\"busy col-12 col-md-auto\">\n    <a href=\"")
//line summary.ego:20
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(relative(req, "/busy"))))
//line summary.ego:20
	_, _ = io.WriteString(w, "\">\n      <span class=\"count\">")
//line summary.ego:21
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(uintWithDelimiter(store.Working().Size(c)))))
//line summary.ego:21
	_, _ = io.WriteString(w, "</span>\n      <span class=\"desc\">")
//line summary.ego:22
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(t(req, "Busy"))))
//line summary.ego:22
	_, _ = io.WriteString(w, "</span>\n    </a>\n  </li>\n  <li class=\"enqueued col-12 col-md-auto\">\n    <a href=\"")
//line summary.ego:26
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(relative(req, "/queues"))))
//line summary.ego:26
	_, _ = io.WriteString(w, "\">\n      <span class=\"count\">")
//line summary.ego:27
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(uintWithDelimiter(enqueuedSize(req)))))
//line summary.ego:27
	_, _ = io.WriteString(w, "</span>\n      <span class=\"desc\">")
//line summary.ego:28
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(t(req, "Enqueued"))))
//line summary.ego:28
	_, _ = io.WriteString(w, "</span>\n    </a>\n  </li>\n  <li class=\"retries col-12 col-md-auto\">\n    <a href=\"")
//line summary.ego:32
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(relative(req, "/retries"))))
//line summary.ego:32
	_, _ = io.WriteString(w, "\">\n      <span class=\"count\">")
//line summary.ego:33
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(uintWithDelimiter(store.Retries().Size(c)))))
//line summary.ego:33
	_, _ = io.WriteString(w, "</span>\n      <span class=\"desc\">")
//line summary.ego:34
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(t(req, "Retries"))))
//line summary.ego:34
	_, _ = io.WriteString(w, "</span>\n    </a>\n  </li>\n  <li class=\"scheduled col-12 col-md-auto\">\n    <a href=\"")
//line summary.ego:38
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(relative(req, "/scheduled"))))
//line summary.ego:38
	_, _ = io.WriteString(w, "\">\n      <span class=\"count\">")
//line summary.ego:39
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(uintWithDelimiter(store.Scheduled().Size(c)))))
//line summary.ego:39
	_, _ = io.WriteString(w, "</span>\n      <span class=\"desc\">")
//line summary.ego:40
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(t(req, "Scheduled"))))
//line summary.ego:40
	_, _ = io.WriteString(w, "</span>\n    </a>\n  </li>\n  <li class=\"dead col-12 col-md-auto\">\n    <a href=\"")
//line summary.ego:44
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(relative(req, "/morgue"))))
//line summary.ego:44
	_, _ = io.WriteString(w, "\">\n      <span class=\"count\">")
//line summary.ego:45
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(uintWithDelimiter(store.Dead().Size(c)))))
//line summary.ego:45
	_, _ = io.WriteString(w, "</span>\n      <span class=\"desc\">")
//line summary.ego:46
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(t(req, "Dead"))))
//line summary.ego:46
	_, _ = io.WriteString(w, "</span>\n    </a>\n  </li>\n</ul>\n")
//line summary.ego:50
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
